In [1]:
import pandas as pd
from models import Standardize, LinearRegression, include, exclude

In [2]:
mlr_test_data = pd.read_csv("multiple_linear_regression_dataset.csv")
mlr_test_data.head()

age  experience  income
0   25           1   30450
1   30           3   35670
2   47           2   31580
3   32           5   40130
4   43          10   47830

In [3]:
variables = exclude('income')
output = include('income')

In [4]:
linear_model = LinearRegression(variables, output)
fitted_model = linear_model >> mlr_test_data

In [5]:
fitted_model.coef_, fitted_model.intercept_

(array([ -99.19535546, 2162.40419192]), 31261.689854101292)

In [6]:
standardize_and_linear = Standardize(variables) >> LinearRegression(variables, output)
fitted_standardized_model = standardize_and_linear >> mlr_test_data

In [7]:
fitted_standardized_model._models[1].coef_, fitted_standardized_model._models[1].intercept_

(array([-994.70371855, 8918.58077748]), 40735.5)

In [8]:
fitted_standardized_model._models[0]._mean, fitted_standardized_model._models[0]._std

(array([39.65,  6.2 ]), array([10.02772472,  4.12438193]))

---